# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Knox < Formula
  desc ""
  homepage "https://github.com/rag594/homebrew-tap"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rag594/knox/releases/download/v0.1.8/knox_Darwin_x86_64.tar.gz"
      sha256 "8c3819d9d39ff137a7849804cac8e96a61ed981f4a47cae0736f39431451874e"

      def install
        bin.install "knox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rag594/knox/releases/download/v0.1.8/knox_Darwin_arm64.tar.gz"
      sha256 "f82c7a2fd38a27fda9a8e0b78f8484a87b1c502736e2cbb469aff48a2dcb68fd"

      def install
        bin.install "knox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rag594/knox/releases/download/v0.1.8/knox_Linux_arm64.tar.gz"
      sha256 "4f45ba7ca60ecf9ca31a599cc88a94824ee2089197d0c11bd9d66b3610f5f499"

      def install
        bin.install "knox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rag594/knox/releases/download/v0.1.8/knox_Linux_x86_64.tar.gz"
      sha256 "d2cfdbe243f21676adfb4ca90ffd623fb238c1db6c864b8c156d8687f1c15aa0"

      def install
        bin.install "knox"
      end
    end
  end
end
